[package]
name = "RBR-GUI"
version = "0.1.0"
build = "src/main.rs"

[lib]
name = "rbrgui"
path = "src/lib.rs"


[[bin]]
name = "RBR-GUI"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }
bincode = "1.3.3"
sysinfo = "0.30.12"
